/**********************************************************************************************************************
 * \file practice.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "practice.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void loop_practice_1(void){
    while(1){
        Can_SendMsg(0x100, "Hello!!!", 8);
        delay_ms(500);
    }
}

void loop_practice_2(void){
    unsigned char CanData[8] = {0, };
    while(1){
        CanData[0]++;
        Can_SendMsg(0x100, CanData, 8);
        delay_ms(100);
    }
}

void loop_practice_3_sender(void){
    while(1){
        Can_SendMsg(0x100, "Hello!!!", 8);
        delay_ms(100);
    }
}

void loop_practice_4(void)
{
    while(1)
    {
        int adcVal = Evadc_readVR();
        float voltage = (float)adcVal*3.3/4095.0;
        my_printf("ADC: %d, Voltage: %.2fV\n", adcVal, voltage);
        delay_ms(100);
    }
}

void loop_practice_5(void)
{
    while(1)
    {
        int adcVal = Evadc_readPR();
        float voltage = (float)adcVal*3.3/4095.0;
        my_printf("ADC: %d, Voltage: %.2fV\n", adcVal, voltage);
        delay_ms(100);
    }
}

void loop_practice_6(void)
{
    unsigned char CanData[8] = {0, };
    while(1)
    {
        int VoltSen = Evadc_readVR();
        unsigned int LightSen = Evadc_readPR();
        CanData[0] = (LightSen & 0xFF00) >> 8;
        CanData[1] = (LightSen & 0xFF);
        CanData[2] = (VoltSen & 0xFF00) >> 8;
        CanData[3] = (VoltSen & 0xFF);
        my_printf("VoltSen(%d), LightSen(%d)\n", VoltSen, LightSen);
        delay_ms(200);
    }
}

void loop_practice_7(void)
{
    volatile int i;
    while (1)
    {
        i = 0;
        while (i++ < 10)
        {
            Can_SendMsg(0x150, (unsigned char *)"ID:0x150", 8);
            delay_ms(100);
        }

        i = 0;
        while (i++ < 10)
        {
            Can_SendMsg(0x7FF, (unsigned char *)"ID:0x7FF", 8);
            delay_ms(100);
        }
    }
}

void loop_practice_8(void)
{
    unsigned char tofValue[3] = {0, };
    unsigned char CanFdData[64] = {0, };
    int VoltSen = 0; unsigned int LightSen = 0;
    while (1)
    {
        VoltSen = Evadc_readVR();
        LightSen = Evadc_readPR();
        CanFdData[0] = (LightSen & 0xFF);
        CanFdData[1] = (LightSen & 0xFF00) >> 8;
        CanFdData[2] = (VoltSen & 0xFF);
        CanFdData[3] = (VoltSen & 0xFF00) >> 8;
        CanFdData[4] = tofValue[2];
        CanFdData[5] = tofValue[1];
        CanFdData[6] = tofValue[0];
        CanFd_SendMsg(0x300, CanFdData, 32);
        delay_ms(100);
    }
}
