/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "IfxScuEru.h"
#include "IfxSrc.h"
#include "_PinMap/IfxScu_PinMap.h"

#include "Platform_Types.h"

#include "Driver_Stm.h"
#include "Driver_Adc.h"

#define SCLK IfxPort_P00_0
#define RCLK IfxPort_P00_1
#define DIO  IfxPort_P00_2

#define LED_R IfxPort_P02_7
#define LED_G IfxPort_P10_5
#define LED_B IfxPort_P10_3

#define LED_D13 IfxPort_P10_2
#define LED_D12 IfxPort_P10_1

IfxCpu_syncEvent cpuSyncEvent = 0;

void initGPIO(void);
void send(uint8_t X);
void send_port(uint8_t X, uint8_t port);
void fnd_display_unit(uint8_t value, uint8_t position);
void fnd_display(uint32 v);

void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);
void AppScheduling(void);


typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;
} TestCntType;

volatile TestCntType stTestCnt;

uint8_t _LED_0F[10] = {0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xF8, 0x80, 0x90};

uint32_t adcResult = 0;
uint32_t adcLight = 0;
uint32_t filteredAdc = 0;


#define LIGHT_DARK_ON   (2500u)
#define LIGHT_DARK_OFF  (2700u)

uint8 isDark = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    initGPIO();
    Driver_Stm_Init();
    Driver_Adc_Init();

    while(1)
    {
        AppScheduling();
    }

    return (1);
}

void colorControl(uint32 adcR)
{
    IfxPort_setPinLow(LED_R.port, LED_R.pinIndex);
    IfxPort_setPinLow(LED_G.port, LED_G.pinIndex);
    IfxPort_setPinLow(LED_B.port, LED_B.pinIndex);

    if (adcR < 1300u)
    {
        IfxPort_setPinHigh(LED_R.port, LED_R.pinIndex);
    }
    else if (adcR < 2600u)
    {
        IfxPort_setPinHigh(LED_G.port, LED_G.pinIndex);
    }
    else
    {
        IfxPort_setPinHigh(LED_B.port, LED_B.pinIndex);
    }
}

void lightControl(uint32 adcL)
{
    if (isDark == 0u)
    {
        if (adcL < LIGHT_DARK_ON)
            isDark = 1u;
    }
    else
    {
        if (adcL > LIGHT_DARK_OFF)
            isDark = 0u;
    }

    if (isDark)
    {
        IfxPort_setPinHigh(LED_D12.port, LED_D12.pinIndex);
        IfxPort_setPinLow(LED_D13.port, LED_D13.pinIndex);
    }
    else
    {
        IfxPort_setPinHigh(LED_D13.port, LED_D13.pinIndex);
        IfxPort_setPinLow(LED_D12.port, LED_D12.pinIndex);
    }

}


void AppTask1ms(void)
{
    static uint8 position = 0;
    uint32 v = filteredAdc;

    switch(position)
    {
        case 0: fnd_display_unit((uint8)(v % 10), 0x1); break;
        case 1: fnd_display_unit((uint8)((v / 10) % 10), 0x2); break;
        case 2: fnd_display_unit((uint8)((v / 100) % 10), 0x4); break;
        case 3: fnd_display_unit((uint8)((v / 1000) % 10), 0x8); break;
        default: break;
    }

    position = (position + 1) % 4;
    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;

    /* ADC test */
    adcResult = Driver_Adc0_DataObtain(7);
    adcLight = Driver_Adc0_DataObtain(6);

    filteredAdc = (uint32_t)(filteredAdc * 0.95f + adcResult * 0.05f);

    colorControl(filteredAdc);
    lightControl(adcLight);

    Driver_Adc0_ConvStart();
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
}

void AppTask1000ms(void)
{
    stTestCnt.u32nuCnt1000ms++;
}

void AppScheduling(void)
{
    if (stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if (stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if (stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }

        if (stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}

void initGPIO(void)
{
    IfxPort_setPinModeOutput(IfxPort_P10_2.port,IfxPort_P10_2.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    IfxPort_setPinLow(LED_D13.port, LED_D13.pinIndex);
    IfxPort_setPinLow(LED_D12.port, LED_D12.pinIndex);

    IfxPort_setPinModeOutput(LED_R.port, LED_R.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LED_G.port, LED_G.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LED_B.port, LED_B.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    IfxPort_setPinLow(LED_R.port, LED_R.pinIndex);
    IfxPort_setPinLow(LED_G.port, LED_G.pinIndex);
    IfxPort_setPinLow(LED_B.port, LED_B.pinIndex);

    IfxPort_setPinModeOutput(IfxPort_P00_0.port, IfxPort_P00_0.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(IfxPort_P00_1.port, IfxPort_P00_1.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(IfxPort_P00_2.port, IfxPort_P00_2.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
}

void fnd_display_unit(uint8_t value, uint8_t position)
{
    uint8_t content = _LED_0F[value];
    send_port(content, position);
}


void fnd_display(uint32 v)
{
    uint8 n1 = (uint8)(v % 10);
    uint8 n2 = (uint8)((v / 10) % 10);
    uint8 n3 = (uint8)((v / 100) % 10);
    uint8 n4 = (uint8)((v / 1000) % 10);

    send_port(_LED_0F[n1], 0x1);
    send_port(_LED_0F[n2], 0x2);
    send_port(_LED_0F[n3], 0x4);
    send_port(_LED_0F[n4], 0x8);
}

void send(uint8_t X)
{
    for (int i = 8; i >= 1; i--)
    {
        if (X & 0x80)
        {
            IfxPort_setPinHigh(DIO.port, DIO.pinIndex);
        }
        else
        {
            IfxPort_setPinLow(DIO.port, DIO.pinIndex);
        }

        X <<= 1;
        IfxPort_setPinLow(SCLK.port, SCLK.pinIndex);
        IfxPort_setPinHigh(SCLK.port, SCLK.pinIndex);
    }
}

void send_port(uint8_t X, uint8_t port)
{
    send(X);
    send(port);
    IfxPort_setPinLow(RCLK.port, RCLK.pinIndex);
    IfxPort_setPinHigh(RCLK.port, RCLK.pinIndex);
}
