/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "IfxStm.h"
#include "IfxCpu_Irq.h"

#include "IfxScuEru.h"

IfxCpu_syncEvent cpuSyncEvent = 0;

void initLED(void);
void initERU(void);
void IfxStmDemo_init(void);

typedef struct
{
    Ifx_STM                 *stmSfr;
    IfxStm_CompareConfig    stmConfig;
    volatile uint8          LedBlink;
    volatile uint32         counter;
} App_Stm;

App_Stm g_Stm;

typedef enum {
    STATE_RED = 0,
    STATE_BLUE = 1,
    STATE_BLINK = 2
} TrafficState;

volatile uint8 stmTickFlag = 0;

volatile uint8 buttonRequest = 0;
volatile uint8 stopFlag = 0;

IFX_INTERRUPT(ISR0, 0, 0x20);
void ISR0(void){
    buttonRequest = 1;
}

IFX_INTERRUPT(STM_Int0Handler, 0, 100);
void STM_Int0Handler(void)
{
    IfxStm_clearCompareFlag(g_Stm.stmSfr, g_Stm.stmConfig.comparator);
    IfxStm_increaseCompare(g_Stm.stmSfr, g_Stm.stmConfig.comparator, 50000000u);

    stmTickFlag = 1;

    IfxCpu_enableInterrupts();
}

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    initLED();
    initERU();
    IfxStmDemo_init();
        
    while(1)
    {
        if (buttonRequest == 1)
        {
            stopFlag ^= 1;
            buttonRequest = 0;
        }

        if (stmTickFlag == 1)
        {
            stmTickFlag = 0;

            if (g_Stm.LedBlink == STATE_BLINK)
            {
                IfxPort_togglePin(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
            }

            if (stopFlag == 0)
            {
                g_Stm.counter++;

                if (g_Stm.counter >= 10)
                {
                    g_Stm.counter = 0;
                    g_Stm.LedBlink = (g_Stm.LedBlink + 1) % 3;

                    if (g_Stm.LedBlink == STATE_RED) {
                        IfxPort_setPinHigh(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
                        IfxPort_setPinLow (IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
                    }
                    else if (g_Stm.LedBlink == STATE_BLUE) {
                        IfxPort_setPinLow (IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
                        IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
                    }
                    else if (g_Stm.LedBlink == STATE_BLINK) {
                        IfxPort_setPinLow (IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
                    }
                }
            }
        }
    }

    return (1);
}

void initLED(void){
    IfxPort_setPinModeOutput(IfxPort_P10_2.port,IfxPort_P10_2.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex,
                             IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    IfxPort_setPinHigh(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
    IfxPort_setPinLow (IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
}

void IfxStmDemo_init(void)
{
    boolean interruptState = IfxCpu_disableInterrupts();

    g_Stm.stmSfr = &MODULE_STM0;
    IfxStm_initCompareConfig(&g_Stm.stmConfig);

    g_Stm.stmConfig.triggerPriority = 100u;
    g_Stm.stmConfig.typeOfService = IfxSrc_Tos_cpu0;
    g_Stm.stmConfig.ticks = 50000000;

    IfxStm_initCompare(g_Stm.stmSfr, &g_Stm.stmConfig);

    IfxCpu_restoreInterrupts(interruptState);
}

void initERU(void){
    //P02.1 -> ERU1(prio 0x20)
    IfxPort_setPinModeInput(IfxPort_P02_1.port, IfxPort_P02_1.pinIndex, IfxPort_InputMode_pullUp);

    IfxScuEru_selectExternalInput(IfxScuEru_InputChannel_2, IfxScuEru_ExternalInputSelection_1);

    IfxScuEru_enableFallingEdgeDetection(IfxScuEru_InputChannel_2);
    IfxScuEru_disableRisingEdgeDetection(IfxScuEru_InputChannel_2);

    IfxScuEru_enableTriggerPulse(IfxScuEru_InputChannel_2);
    IfxScuEru_connectTrigger(IfxScuEru_InputChannel_2, IfxScuEru_InputNodePointer_1);

    IfxScuEru_setInterruptGatingPattern(IfxScuEru_OutputChannel_1,
                                        IfxScuEru_InterruptGatingPattern_alwaysActive);
    IfxScuEru_setFlagPatternDetection(IfxScuEru_OutputChannel_1, IfxScuEru_InputChannel_2, TRUE);

    IfxScuEru_clearEventFlag(IfxScuEru_InputChannel_2);

    IfxSrc_init(&SRC_SCU_SCU_ERU1, IfxSrc_Tos_cpu0, 0x20u);
    IfxSrc_enable(&SRC_SCU_SCU_ERU1);
}
