/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title GTM TOM PWM generation
 * \abstract GTM TOM is used to generate a PWM signal, which is driving the intensity of an LED.
 * \description The LED is driven by pin 2 of the port 10. The state of the pin is controlled by the PWM signal
 *              generated by the TOM timer of GTM.
 *
 * \name GTM_TOM_PWM_1_KIT_TC275_SB
 * \version V1.0.1
 * \board hitex ShieldBuddy, KIT_AURIX_TC275_ARD_SB, TC27xTP_D-Step
 * \keywords AURIX, GTM, GTM_TOM_PWM_1, PWM, general timer, timer
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_GTM_TOM_PWM_1_KIT_TC275_SB-TR-v01_00_01-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC27D_iLLD_UM_1_0_1_12_0.chm
 * \lastUpdated 2020-12-18
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "IfxScuEru.h"
#include "IfxSrc.h"
#include "_PinMap/IfxScu_PinMap.h"

#include "Platform_Types.h"

#include "Driver_Stm.h"
#include "Driver_Adc.h"

void initGPIO(void);

void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);
void AppScheduling(void);

typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;
} TestCntType;

volatile TestCntType stTestCnt;

IfxCpu_syncEvent g_cpuSyncEvent = 0;

int babySharkMelody[] = {
    2,14,4,14,7,14,7,14,7,14,7,14,7,14,7,14,7,14,
    2,14,4,14,7,14,14,14,7,14,7,14,7,14,7,14,7,14,
    2,14,4,14,7,14,14,14,7,14,7,14,7,14,7,14,7,14,7,14,7,14,6,14,6,14
};

int babySharkDurations[] = {
    500, 5, 500, 5, 250, 5, 250, 5, 250, 5, 125, 5, 250, 5, 125, 5, 250, 5,
    250, 5, 250, 5, 250, 5, 250, 5, 250, 5, 125, 5, 250, 5, 125, 5, 250, 5,
    250, 5, 250, 5, 250, 5, 250, 5, 250, 5, 125, 5, 250, 5, 125, 5, 250, 5, 250, 5, 250, 5, 250, 5, 250, 500
};
int length = sizeof(babySharkMelody) / sizeof(babySharkMelody[0]);

int g_noteIdx = 0;
int g_msTimer = 0;
boolean g_playMusic = TRUE;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initGPIO();
    Driver_Stm_Init();
    Driver_Adc_Init();

    /* Initialize GTM TOM module */
    initGtmTomPwm();


    while(1)
    {
        AppScheduling();
    }

    return (1);
}

void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;

    if (g_playMusic == TRUE)
    {
        if (g_msTimer > 0)
        {
            g_msTimer--;
        }
        else
        {
            g_noteIdx++;

            if (g_noteIdx >= length)
            {
                g_noteIdx = 0;
            }

            makeSound(babySharkMelody[g_noteIdx]);

            g_msTimer = babySharkDurations[g_noteIdx];
        }
    }
    else
    {
        setDutyCycle(0);
    }
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;

    static uint8 btn0_cnt = 0;

    if (IfxPort_getPinState(IfxPort_P02_0.port, IfxPort_P02_0.pinIndex) == FALSE)
    {
        btn0_cnt++;
        if (btn0_cnt == 3)
        {
            g_playMusic = !g_playMusic;
        }
    }
    else
    {
        btn0_cnt = 0;
    }
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
}

void AppTask1000ms(void)
{
    stTestCnt.u32nuCnt1000ms++;
}

void AppScheduling(void)
{
    if (stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if (stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if (stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }

        if (stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}

void initGPIO(void)
{
    IfxPort_setPinModeInput(IfxPort_P02_0.port, IfxPort_P02_0.pinIndex, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(IfxPort_P02_1.port, IfxPort_P02_1.pinIndex, IfxPort_InputMode_pullUp);
}
